[package]
name = "apollo-audio-worker"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
apollo-ipc = { path = "../ipc" }
async-trait = { workspace = true }
dotenvy = { workspace = true }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "stream"] }
tokio = { workspace = true, features = ["rt-multi-thread", "net", "io-util", "macros", "signal"] }
songbird = { workspace = true, features = ["driver", "rustls", "tungstenite"] }
symphonia = { version = "0.5", features = ["aac", "isomp4"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
