[package]
name = "apollo-ipc"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
bincode = { version = "2", features = ["serde"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util"] }
uuid = { workspace = true, features = ["serde"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
