[package]
name = "apollo-ipc"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }
bincode = { version = "2", features = ["serde"] }
tokio = { version = "1.53", features = ["io-util"] }
uuid = { version = "1", features = ["serde"] }

[dev-dependencies]
tokio = { version = "1.53", features = ["macros", "rt"] }
